set_property BEL C6LUT [get_cells apuf/transition]
set_property LOC SLICE_X101Y100 [get_cells apuf/transition]
set_property BEL D6LUT [get_cells {apuf/path0/genblk1[0].chblock/mux}]
set_property LOC SLICE_X97Y99 [get_cells {apuf/path0/genblk1[0].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk1[0].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk1[0].chblock/mux}]
set_property LOC SLICE_X101Y99 [get_cells {apuf/path1/genblk1[0].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk1[0].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk1[1].chblock/mux}]
set_property LOC SLICE_X97Y98 [get_cells {apuf/path0/genblk1[1].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk1[1].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk1[1].chblock/mux}]
set_property LOC SLICE_X101Y98 [get_cells {apuf/path1/genblk1[1].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk1[1].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk1[2].chblock/mux}]
set_property LOC SLICE_X97Y97 [get_cells {apuf/path0/genblk1[2].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk1[2].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk1[2].chblock/mux}]
set_property LOC SLICE_X101Y97 [get_cells {apuf/path1/genblk1[2].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk1[2].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk1[3].chblock/mux}]
set_property LOC SLICE_X97Y96 [get_cells {apuf/path0/genblk1[3].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk1[3].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk1[3].chblock/mux}]
set_property LOC SLICE_X101Y96 [get_cells {apuf/path1/genblk1[3].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk1[3].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk1[4].chblock/mux}]
set_property LOC SLICE_X97Y95 [get_cells {apuf/path0/genblk1[4].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk1[4].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk1[4].chblock/mux}]
set_property LOC SLICE_X101Y95 [get_cells {apuf/path1/genblk1[4].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk1[4].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk1[5].chblock/mux}]
set_property LOC SLICE_X97Y94 [get_cells {apuf/path0/genblk1[5].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk1[5].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk1[5].chblock/mux}]
set_property LOC SLICE_X101Y94 [get_cells {apuf/path1/genblk1[5].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk1[5].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk1[6].chblock/mux}]
set_property LOC SLICE_X97Y93 [get_cells {apuf/path0/genblk1[6].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk1[6].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk1[6].chblock/mux}]
set_property LOC SLICE_X101Y93 [get_cells {apuf/path1/genblk1[6].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk1[6].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk1[7].chblock/mux}]
set_property LOC SLICE_X97Y92 [get_cells {apuf/path0/genblk1[7].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk1[7].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk1[7].chblock/mux}]
set_property LOC SLICE_X101Y92 [get_cells {apuf/path1/genblk1[7].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk1[7].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk1[8].chblock/mux}]
set_property LOC SLICE_X97Y91 [get_cells {apuf/path0/genblk1[8].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk1[8].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk1[8].chblock/mux}]
set_property LOC SLICE_X101Y91 [get_cells {apuf/path1/genblk1[8].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk1[8].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk1[9].chblock/mux}]
set_property LOC SLICE_X97Y90 [get_cells {apuf/path0/genblk1[9].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk1[9].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk1[9].chblock/mux}]
set_property LOC SLICE_X101Y90 [get_cells {apuf/path1/genblk1[9].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk1[9].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk1[10].chblock/mux}]
set_property LOC SLICE_X97Y89 [get_cells {apuf/path0/genblk1[10].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk1[10].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk1[10].chblock/mux}]
set_property LOC SLICE_X101Y89 [get_cells {apuf/path1/genblk1[10].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk1[10].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk1[11].chblock/mux}]
set_property LOC SLICE_X97Y88 [get_cells {apuf/path0/genblk1[11].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk1[11].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk1[11].chblock/mux}]
set_property LOC SLICE_X101Y88 [get_cells {apuf/path1/genblk1[11].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk1[11].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk1[12].chblock/mux}]
set_property LOC SLICE_X97Y87 [get_cells {apuf/path0/genblk1[12].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk1[12].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk1[12].chblock/mux}]
set_property LOC SLICE_X101Y87 [get_cells {apuf/path1/genblk1[12].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk1[12].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk1[13].chblock/mux}]
set_property LOC SLICE_X97Y86 [get_cells {apuf/path0/genblk1[13].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk1[13].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk1[13].chblock/mux}]
set_property LOC SLICE_X101Y86 [get_cells {apuf/path1/genblk1[13].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk1[13].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk1[14].chblock/mux}]
set_property LOC SLICE_X97Y85 [get_cells {apuf/path0/genblk1[14].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk1[14].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk1[14].chblock/mux}]
set_property LOC SLICE_X101Y85 [get_cells {apuf/path1/genblk1[14].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk1[14].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk1[15].chblock/mux}]
set_property LOC SLICE_X97Y84 [get_cells {apuf/path0/genblk1[15].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk1[15].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk1[15].chblock/mux}]
set_property LOC SLICE_X101Y84 [get_cells {apuf/path1/genblk1[15].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk1[15].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk1[16].chblock/mux}]
set_property LOC SLICE_X97Y83 [get_cells {apuf/path0/genblk1[16].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk1[16].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk1[16].chblock/mux}]
set_property LOC SLICE_X101Y83 [get_cells {apuf/path1/genblk1[16].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk1[16].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk1[17].chblock/mux}]
set_property LOC SLICE_X97Y82 [get_cells {apuf/path0/genblk1[17].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk1[17].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk1[17].chblock/mux}]
set_property LOC SLICE_X101Y82 [get_cells {apuf/path1/genblk1[17].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk1[17].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk1[18].chblock/mux}]
set_property LOC SLICE_X97Y81 [get_cells {apuf/path0/genblk1[18].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk1[18].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk1[18].chblock/mux}]
set_property LOC SLICE_X101Y81 [get_cells {apuf/path1/genblk1[18].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk1[18].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk1[19].chblock/mux}]
set_property LOC SLICE_X97Y80 [get_cells {apuf/path0/genblk1[19].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk1[19].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk1[19].chblock/mux}]
set_property LOC SLICE_X101Y80 [get_cells {apuf/path1/genblk1[19].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk1[19].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk1[20].chblock/mux}]
set_property LOC SLICE_X97Y79 [get_cells {apuf/path0/genblk1[20].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk1[20].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk1[20].chblock/mux}]
set_property LOC SLICE_X101Y79 [get_cells {apuf/path1/genblk1[20].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk1[20].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk1[21].chblock/mux}]
set_property LOC SLICE_X97Y78 [get_cells {apuf/path0/genblk1[21].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk1[21].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk1[21].chblock/mux}]
set_property LOC SLICE_X101Y78 [get_cells {apuf/path1/genblk1[21].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk1[21].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk1[22].chblock/mux}]
set_property LOC SLICE_X97Y77 [get_cells {apuf/path0/genblk1[22].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk1[22].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk1[22].chblock/mux}]
set_property LOC SLICE_X101Y77 [get_cells {apuf/path1/genblk1[22].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk1[22].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk1[23].chblock/mux}]
set_property LOC SLICE_X97Y76 [get_cells {apuf/path0/genblk1[23].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk1[23].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk1[23].chblock/mux}]
set_property LOC SLICE_X101Y76 [get_cells {apuf/path1/genblk1[23].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk1[23].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk1[24].chblock/mux}]
set_property LOC SLICE_X97Y75 [get_cells {apuf/path0/genblk1[24].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk1[24].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk1[24].chblock/mux}]
set_property LOC SLICE_X101Y75 [get_cells {apuf/path1/genblk1[24].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk1[24].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk1[25].chblock/mux}]
set_property LOC SLICE_X97Y74 [get_cells {apuf/path0/genblk1[25].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk1[25].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk1[25].chblock/mux}]
set_property LOC SLICE_X101Y74 [get_cells {apuf/path1/genblk1[25].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk1[25].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk1[26].chblock/mux}]
set_property LOC SLICE_X97Y73 [get_cells {apuf/path0/genblk1[26].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk1[26].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk1[26].chblock/mux}]
set_property LOC SLICE_X101Y73 [get_cells {apuf/path1/genblk1[26].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk1[26].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk1[27].chblock/mux}]
set_property LOC SLICE_X97Y72 [get_cells {apuf/path0/genblk1[27].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk1[27].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk1[27].chblock/mux}]
set_property LOC SLICE_X101Y72 [get_cells {apuf/path1/genblk1[27].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk1[27].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk1[28].chblock/mux}]
set_property LOC SLICE_X97Y71 [get_cells {apuf/path0/genblk1[28].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk1[28].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk1[28].chblock/mux}]
set_property LOC SLICE_X101Y71 [get_cells {apuf/path1/genblk1[28].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk1[28].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk1[29].chblock/mux}]
set_property LOC SLICE_X97Y70 [get_cells {apuf/path0/genblk1[29].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk1[29].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk1[29].chblock/mux}]
set_property LOC SLICE_X101Y70 [get_cells {apuf/path1/genblk1[29].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk1[29].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk1[30].chblock/mux}]
set_property LOC SLICE_X97Y69 [get_cells {apuf/path0/genblk1[30].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk1[30].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk1[30].chblock/mux}]
set_property LOC SLICE_X101Y69 [get_cells {apuf/path1/genblk1[30].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk1[30].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk1[31].chblock/mux}]
set_property LOC SLICE_X97Y68 [get_cells {apuf/path0/genblk1[31].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk1[31].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk1[31].chblock/mux}]
set_property LOC SLICE_X101Y68 [get_cells {apuf/path1/genblk1[31].chblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk1[31].chblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk2[0].adjblock/mux}]
set_property LOC SLICE_X97Y67 [get_cells {apuf/path0/genblk2[0].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk2[0].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk2[0].adjblock/mux}]
set_property LOC SLICE_X101Y67 [get_cells {apuf/path1/genblk2[0].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk2[0].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk2[1].adjblock/mux}]
set_property LOC SLICE_X97Y66 [get_cells {apuf/path0/genblk2[1].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk2[1].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk2[1].adjblock/mux}]
set_property LOC SLICE_X101Y66 [get_cells {apuf/path1/genblk2[1].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk2[1].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk2[2].adjblock/mux}]
set_property LOC SLICE_X97Y65 [get_cells {apuf/path0/genblk2[2].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk2[2].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk2[2].adjblock/mux}]
set_property LOC SLICE_X101Y65 [get_cells {apuf/path1/genblk2[2].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk2[2].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk2[3].adjblock/mux}]
set_property LOC SLICE_X97Y64 [get_cells {apuf/path0/genblk2[3].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk2[3].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk2[3].adjblock/mux}]
set_property LOC SLICE_X101Y64 [get_cells {apuf/path1/genblk2[3].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk2[3].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk2[4].adjblock/mux}]
set_property LOC SLICE_X97Y63 [get_cells {apuf/path0/genblk2[4].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk2[4].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk2[4].adjblock/mux}]
set_property LOC SLICE_X101Y63 [get_cells {apuf/path1/genblk2[4].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk2[4].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk2[5].adjblock/mux}]
set_property LOC SLICE_X97Y62 [get_cells {apuf/path0/genblk2[5].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk2[5].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk2[5].adjblock/mux}]
set_property LOC SLICE_X101Y62 [get_cells {apuf/path1/genblk2[5].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk2[5].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk2[6].adjblock/mux}]
set_property LOC SLICE_X97Y61 [get_cells {apuf/path0/genblk2[6].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk2[6].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk2[6].adjblock/mux}]
set_property LOC SLICE_X101Y61 [get_cells {apuf/path1/genblk2[6].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk2[6].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk2[7].adjblock/mux}]
set_property LOC SLICE_X97Y60 [get_cells {apuf/path0/genblk2[7].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk2[7].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk2[7].adjblock/mux}]
set_property LOC SLICE_X101Y60 [get_cells {apuf/path1/genblk2[7].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk2[7].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk2[8].adjblock/mux}]
set_property LOC SLICE_X97Y59 [get_cells {apuf/path0/genblk2[8].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk2[8].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk2[8].adjblock/mux}]
set_property LOC SLICE_X101Y59 [get_cells {apuf/path1/genblk2[8].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk2[8].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk2[9].adjblock/mux}]
set_property LOC SLICE_X97Y58 [get_cells {apuf/path0/genblk2[9].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk2[9].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk2[9].adjblock/mux}]
set_property LOC SLICE_X101Y58 [get_cells {apuf/path1/genblk2[9].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk2[9].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk2[10].adjblock/mux}]
set_property LOC SLICE_X97Y57 [get_cells {apuf/path0/genblk2[10].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk2[10].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk2[10].adjblock/mux}]
set_property LOC SLICE_X101Y57 [get_cells {apuf/path1/genblk2[10].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk2[10].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk2[11].adjblock/mux}]
set_property LOC SLICE_X97Y56 [get_cells {apuf/path0/genblk2[11].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk2[11].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk2[11].adjblock/mux}]
set_property LOC SLICE_X101Y56 [get_cells {apuf/path1/genblk2[11].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk2[11].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk2[12].adjblock/mux}]
set_property LOC SLICE_X97Y55 [get_cells {apuf/path0/genblk2[12].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk2[12].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk2[12].adjblock/mux}]
set_property LOC SLICE_X101Y55 [get_cells {apuf/path1/genblk2[12].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk2[12].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk2[13].adjblock/mux}]
set_property LOC SLICE_X97Y54 [get_cells {apuf/path0/genblk2[13].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk2[13].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk2[13].adjblock/mux}]
set_property LOC SLICE_X101Y54 [get_cells {apuf/path1/genblk2[13].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk2[13].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk2[14].adjblock/mux}]
set_property LOC SLICE_X97Y53 [get_cells {apuf/path0/genblk2[14].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk2[14].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk2[14].adjblock/mux}]
set_property LOC SLICE_X101Y53 [get_cells {apuf/path1/genblk2[14].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk2[14].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk2[15].adjblock/mux}]
set_property LOC SLICE_X97Y52 [get_cells {apuf/path0/genblk2[15].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk2[15].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk2[15].adjblock/mux}]
set_property LOC SLICE_X101Y52 [get_cells {apuf/path1/genblk2[15].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk2[15].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk2[16].adjblock/mux}]
set_property LOC SLICE_X97Y51 [get_cells {apuf/path0/genblk2[16].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk2[16].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk2[16].adjblock/mux}]
set_property LOC SLICE_X101Y51 [get_cells {apuf/path1/genblk2[16].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk2[16].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk2[17].adjblock/mux}]
set_property LOC SLICE_X97Y50 [get_cells {apuf/path0/genblk2[17].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk2[17].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk2[17].adjblock/mux}]
set_property LOC SLICE_X101Y50 [get_cells {apuf/path1/genblk2[17].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk2[17].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk2[18].adjblock/mux}]
set_property LOC SLICE_X97Y49 [get_cells {apuf/path0/genblk2[18].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk2[18].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk2[18].adjblock/mux}]
set_property LOC SLICE_X101Y49 [get_cells {apuf/path1/genblk2[18].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk2[18].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk2[19].adjblock/mux}]
set_property LOC SLICE_X97Y48 [get_cells {apuf/path0/genblk2[19].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk2[19].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk2[19].adjblock/mux}]
set_property LOC SLICE_X101Y48 [get_cells {apuf/path1/genblk2[19].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk2[19].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk2[20].adjblock/mux}]
set_property LOC SLICE_X97Y47 [get_cells {apuf/path0/genblk2[20].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk2[20].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk2[20].adjblock/mux}]
set_property LOC SLICE_X101Y47 [get_cells {apuf/path1/genblk2[20].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk2[20].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk2[21].adjblock/mux}]
set_property LOC SLICE_X97Y46 [get_cells {apuf/path0/genblk2[21].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk2[21].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk2[21].adjblock/mux}]
set_property LOC SLICE_X101Y46 [get_cells {apuf/path1/genblk2[21].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk2[21].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk2[22].adjblock/mux}]
set_property LOC SLICE_X97Y45 [get_cells {apuf/path0/genblk2[22].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk2[22].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk2[22].adjblock/mux}]
set_property LOC SLICE_X101Y45 [get_cells {apuf/path1/genblk2[22].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk2[22].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk2[23].adjblock/mux}]
set_property LOC SLICE_X97Y44 [get_cells {apuf/path0/genblk2[23].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk2[23].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk2[23].adjblock/mux}]
set_property LOC SLICE_X101Y44 [get_cells {apuf/path1/genblk2[23].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk2[23].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk2[24].adjblock/mux}]
set_property LOC SLICE_X97Y43 [get_cells {apuf/path0/genblk2[24].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk2[24].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk2[24].adjblock/mux}]
set_property LOC SLICE_X101Y43 [get_cells {apuf/path1/genblk2[24].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk2[24].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk2[25].adjblock/mux}]
set_property LOC SLICE_X97Y42 [get_cells {apuf/path0/genblk2[25].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk2[25].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk2[25].adjblock/mux}]
set_property LOC SLICE_X101Y42 [get_cells {apuf/path1/genblk2[25].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk2[25].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk2[26].adjblock/mux}]
set_property LOC SLICE_X97Y41 [get_cells {apuf/path0/genblk2[26].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk2[26].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk2[26].adjblock/mux}]
set_property LOC SLICE_X101Y41 [get_cells {apuf/path1/genblk2[26].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk2[26].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk2[27].adjblock/mux}]
set_property LOC SLICE_X97Y40 [get_cells {apuf/path0/genblk2[27].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk2[27].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk2[27].adjblock/mux}]
set_property LOC SLICE_X101Y40 [get_cells {apuf/path1/genblk2[27].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk2[27].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk2[28].adjblock/mux}]
set_property LOC SLICE_X97Y39 [get_cells {apuf/path0/genblk2[28].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk2[28].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk2[28].adjblock/mux}]
set_property LOC SLICE_X101Y39 [get_cells {apuf/path1/genblk2[28].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk2[28].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk2[29].adjblock/mux}]
set_property LOC SLICE_X97Y38 [get_cells {apuf/path0/genblk2[29].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk2[29].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk2[29].adjblock/mux}]
set_property LOC SLICE_X101Y38 [get_cells {apuf/path1/genblk2[29].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk2[29].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk2[30].adjblock/mux}]
set_property LOC SLICE_X97Y37 [get_cells {apuf/path0/genblk2[30].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk2[30].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk2[30].adjblock/mux}]
set_property LOC SLICE_X101Y37 [get_cells {apuf/path1/genblk2[30].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk2[30].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path0/genblk2[31].adjblock/mux}]
set_property LOC SLICE_X97Y36 [get_cells {apuf/path0/genblk2[31].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path0/genblk2[31].adjblock/mux}]
set_property BEL D6LUT [get_cells {apuf/path1/genblk2[31].adjblock/mux}]
set_property LOC SLICE_X101Y36 [get_cells {apuf/path1/genblk2[31].adjblock/mux}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1} [get_cells {apuf/path1/genblk2[31].adjblock/mux}]
set_property BEL DFF [get_cells apuf/arbiter/inst_RSP]
set_property LOC SLICE_X101Y35 [get_cells apuf/arbiter/inst_RSP]

